language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install flake8 flake8-docstrings bandit twine
# command to run tests

style:
  - flake8 .

security:
  - bandit -r .

build:
  - python setup.py sdis

check:
  - twine check dist/*

