language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install flake8 flake8-docstrings bandit twine
# command to run tests

jobs:
  include:
  - stage: lint
    script: flake8 .
  - stage: sec-audit
    script: bandit -r .
  - stage: build
    script: python setup.py sdist
  - stage: check-build
    script: twine check dist/*

